<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend"><?php echo $this->__("Client Information") ?></h4>
    </div>
    <div id="client_account_fieds">
        <div class="fieldset " id="main">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label"><label for="group_id">Client PO# </label></td>
						<td class="value">
							<input id="client_po" name="order[client][client_po]" value="" class="input-text" type="text"> 
						</td>
					</tr>
					<tr>
						<td class="label"><label for="email">Reference Order ID</label></td>
						<td class="value">
							<input id="order_ids" name="order[client][order_ids]" value="" class=" input-text " type="text">            
						</td>
					</tr>
				</tbody>
			</table>
		</div>
        </div>
    </div>
</div>
